export const PRODUCTS = [
  {
    id: 1,
    name: 'Vitamin C Cleanser',
    category: 'Cleanser',
    size: '100 ml',
    price: 18,
    comparePrice: 22,
    bg: '#9AAAE0',
    shape: 'tube',
    color: '#D9532D',
    textColor: '#F5EBDD',
    sub: 'Brightening · Energizing',
    badge: 'Best seller',
    rating: 4.8,
    reviews: 2341,
    image: '/images/product-cleanser.jpg',
    description:
      'A brightening daily cleanser powered by Vitamin C that delivers a fresh start for radiant skin. Removes impurities while energizing and evening skin tone.',
    ingredients: 'Ascorbic Acid, Glycolic Acid, Aloe Vera, Niacinamide',
  },
  {
    id: 2,
    name: 'Hydrating Gel',
    category: 'Moisturizer',
    size: '150 ml',
    price: 22,
    bg: '#9AAAE0',
    shape: 'tube',
    color: '#E8568C',
    textColor: '#7A1040',
    sub: 'Lightweight · Daily Moisture',
    rating: 4.9,
    reviews: 1804,
    image: '/images/product-gel.jpg',
    description:
      'A soft, plump, glowing skin gel for lightweight daily moisture. Formulated with hyaluronic acid and ceramides for all-day hydration without heaviness.',
    ingredients: 'Hyaluronic Acid, Ceramides, Centella Asiatica, Aloe Vera',
  },
  {
    id: 3,
    name: 'Hydrating Serum',
    category: 'Serum',
    size: '50 ml',
    price: 26,
    bg: '#9AAAE0',
    shape: 'pump',
    color: '#FAFAF6',
    textColor: '#2D7A6A',
    accentColor: '#5A9E8C',
    sub: 'Hyaluronic Acid · Peptides',
    rating: 4.9,
    reviews: 983,
    image: '/images/product-serum.jpg',
    description:
      'A deeply hydrating serum powered by hyaluronic acid and peptides to restore moisture balance and improve skin elasticity. Deep hydration for balanced skin.',
    ingredients: 'Sodium Hyaluronate, Peptides, Vitamin E, Panthenol',
  },
  {
    id: 4,
    name: 'Repair Cream',
    category: 'Cream',
    size: '60 ml',
    price: 28,
    bg: '#9AAAE0',
    shape: 'jar',
    color: '#F5C4A8',
    textColor: '#A04030',
    sub: 'Barrier Support · Nourishment',
    rating: 4.7,
    reviews: 762,
    image: '/images/product-cream.jpg',
    description:
      'A nourishing cream designed to strengthen the skin barrier and restore moisture. Barrier support + nourishment to restore and strengthen your skin overnight.',
    ingredients: 'Shea Butter, Ceramides, Squalane, Oat Extract',
  },
  {
    id: 5,
    name: 'Calming Cleanser',
    category: 'Cleanser',
    size: '30 ml',
    price: 16,
    bg: '#9AAAE0',
    shape: 'tube',
    color: '#B8D44A',
    textColor: '#2D5A1A',
    sub: 'For Sensitive Skin',
    badge: 'New',
    rating: 4.8,
    reviews: 412,
    image: '/images/product-cleanser-calming.jpg',
    description:
      'A gentle cleanse without irritation, formulated specifically for sensitive skin. Calms redness and removes impurities while maintaining the skin\'s natural moisture barrier.',
    ingredients: 'Centella Asiatica, Green Tea Extract, Chamomile, Aloe Vera',
  },
];
